#!/bin/bash

# TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
TheSkyX_Install=`/usr/bin/find ~/Library/Application\ Support/Software\ Bisque/ -name TheSkyXInstallPath.txt`
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    TheSkyX_Path=`/usr/bin/find /Applications -maxdepth 3 -name TheSkyX\*.app`
    if [ -d "$TheSkyX_Path" ]; then
		TheSkyX_Path="${TheSkyX_Path}/Contents"
    else
	   echo TheSkyX application was not found.
    	exit 1
	 fi
else
	TheSkyX_Path=$(<"$TheSkyX_Install")
fi

echo "Installing to $TheSkyX_Path"

if [ ! -d "$TheSkyX_Path" ]; then
    echo Coudln't find TheSkyX application location
    exit 1
fi

cp "/tmp/DomePro_X2/domelist DomePro.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
cp "/tmp/DomePro_X2/DomePro.ui" "$TheSkyX_Path/Resources/Common/PlugIns/DomePlugIns/"
cp "/tmp/DomePro_X2/DomeProDiag.ui" "$TheSkyX_Path/Resources/Common/PlugIns/DomePlugIns/"
cp "/tmp/DomePro_X2/Astrometric.png" "$TheSkyX_Path/Resources/Common/PlugIns/DomePlugIns/"
cp "/tmp/DomePro_X2/libDomePro.dylib" "$TheSkyX_Path/Resources/Common/PlugIns/DomePlugIns/"

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/domelist DomePro.txt"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/DomePlugIns/DomePro.ui"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/DomePlugIns/DomeProDiag.ui"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/DomePlugIns/Astrometric.png"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/DomePlugIns/libDomePro.dylib"
fi
chmod  755 "$TheSkyX_Path/Resources/Common/PlugIns/DomePlugIns/libDomePro.dylib"
rm -rf /tmp/DomePro_X2

