#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"$TheSkyX_Install")
echo "Installing to $TheSkyX_Path"


if [ ! -d "$TheSkyX_Path" ]; then
    echo "Coudln't find TheSkyX application location"
    exit 1
fi

if [ -d "$TheSkyX_Path/Resources/Common/PlugIns64" ]; then
	PLUGINS_DIR="PlugIns64"
else
	PLUGINS_DIR="PlugIns"
fi

echo "Installing in $TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/"

cp "/tmp/DomePro_X2/domelist DomePro.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp "/tmp/DomePro_X2/domepro.ui" "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp "/tmp/DomePro_X2/domeprodiag.ui" "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp "/tmp/DomePro_X2/domeshutter.ui" "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp "/tmp/DomePro_X2/dometimeouts.ui" "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp "/tmp/DomePro_X2/Astrometric.png" "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp "/tmp/DomePro_X2/libDomePro.dylib" "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/domelist DomePro.txt"
	chown $app_owner "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/domepro.ui"
	chown $app_owner "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/domeprodiag.ui"
	chown $app_owner "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/domeshutter.ui"
	chown $app_owner "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/dometimeouts.ui"
	chown $app_owner "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/Astrometric.png"
	chown $app_owner "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/libDomePro.dylib"
fi
chmod  755 "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/libDomePro.dylib"
rm -rf /tmp/DomePro_X2

